# Generated by Django 4.2.4 on 2023-08-18 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(
                default=django.utils.timezone.now, max_length=150, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="subtitle",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(upload_to="articles/"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
