# Generated by Django 4.2.4 on 2023-08-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_date_blog_created_at_blog_slug_blog_subtitle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
