# Generated by Django 4.2.4 on 2023-08-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blog_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
