# Generated by Django 4.2.4 on 2023-08-20 14:19

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_blog_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=django_quill.fields.QuillField(),
        ),
    ]
