# Generated by Django 4.2.4 on 2023-08-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_blog_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="blog",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
