# Generated by Django 4.2.4 on 2023-08-20 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_blog_options_blog_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["-created_at"]},
        ),
    ]
