# Generated by Django 4.2.4 on 2023-08-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_blog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(default="ok", max_length=300),
            preserve_default=False,
        ),
    ]
