# Generated by Django 4.2.4 on 2023-08-21 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_category_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="published",
        ),
    ]
